CREATE TABLE USER  
(  
UID INT NOT NULL auto_increment,  
UNAME VARCHAR(12) NOT NULL unique,    
PASS INT NOT NULL,  
ROLE VARCHAR(10) NOT NULL,  
PRIMARY KEY(UID)  
); 

CREATE TABLE USER_PROFILE  
(  
UID INT ,  
FNAME VARCHAR(12) NOT NULL,    
LNAME VARCHAR(12) NOT NULL,  
EMAIL VARCHAR(20) NOT NULL, 
Phone VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(20) NOT NULL, 
PRIMARY KEY (UID),
foreign key (UID) references USER(UID)
);  

CREATE TABLE PRODUCT  
(  
PID INT NOT NULL auto_increment,  
PNAME VARCHAR(30) NOT NULL,    
CATEGORY VARCHAR(12) NOT NULL,  
PRICE INT NOT NULL, 
UID INT NOT NULL,
DESP VARCHAR(100) NOT NULL, 
PHOTO mediumblob,
PRIMARY KEY (PID),
foreign key (UID) references USER(UID)
); 